# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: kartoza/postgis
    volumes:
      - ./postgis-data:/var/lib/postgresql
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=geolocdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"
      